// Code generated by protoc-gen-go. DO NOT EDIT.
// source: block.proto

/*
Package n3 is a generated protocol buffer package.

It is generated from these files:
	block.proto

It has these top-level messages:
	SPOTuple
	Block
*/
package n3

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// core message type for lowest-level data tuples
type SPOTuple struct {
	Subject   string `protobuf:"bytes,1,opt,name=Subject" json:"Subject,omitempty"`
	Object    string `protobuf:"bytes,2,opt,name=Object" json:"Object,omitempty"`
	Predicate string `protobuf:"bytes,3,opt,name=Predicate" json:"Predicate,omitempty"`
	Version   uint64 `protobuf:"varint,4,opt,name=Version" json:"Version,omitempty"`
	Context   string `protobuf:"bytes,5,opt,name=Context" json:"Context,omitempty"`
}

func (m *SPOTuple) Reset()                    { *m = SPOTuple{} }
func (m *SPOTuple) String() string            { return proto.CompactTextString(m) }
func (*SPOTuple) ProtoMessage()               {}
func (*SPOTuple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SPOTuple) GetSubject() string {
	if m != nil {
		return m.Subject
	}
	return ""
}

func (m *SPOTuple) GetObject() string {
	if m != nil {
		return m.Object
	}
	return ""
}

func (m *SPOTuple) GetPredicate() string {
	if m != nil {
		return m.Predicate
	}
	return ""
}

func (m *SPOTuple) GetVersion() uint64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SPOTuple) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

type Block struct {
	BlockId       string    `protobuf:"bytes,1,opt,name=BlockId" json:"BlockId,omitempty"`
	Data          *SPOTuple `protobuf:"bytes,2,opt,name=Data" json:"Data,omitempty"`
	PrevBlockHash string    `protobuf:"bytes,3,opt,name=PrevBlockHash" json:"PrevBlockHash,omitempty"`
	Hash          string    `protobuf:"bytes,4,opt,name=Hash" json:"Hash,omitempty"`
	Sig           string    `protobuf:"bytes,5,opt,name=Sig" json:"Sig,omitempty"`
	Author        string    `protobuf:"bytes,6,opt,name=Author" json:"Author,omitempty"`
	Sender        string    `protobuf:"bytes,7,opt,name=Sender" json:"Sender,omitempty"`
}

func (m *Block) Reset()                    { *m = Block{} }
func (m *Block) String() string            { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()               {}
func (*Block) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Block) GetBlockId() string {
	if m != nil {
		return m.BlockId
	}
	return ""
}

func (m *Block) GetData() *SPOTuple {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Block) GetPrevBlockHash() string {
	if m != nil {
		return m.PrevBlockHash
	}
	return ""
}

func (m *Block) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *Block) GetSig() string {
	if m != nil {
		return m.Sig
	}
	return ""
}

func (m *Block) GetAuthor() string {
	if m != nil {
		return m.Author
	}
	return ""
}

func (m *Block) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func init() {
	proto.RegisterType((*SPOTuple)(nil), "n3.SPOTuple")
	proto.RegisterType((*Block)(nil), "n3.Block")
}

func init() { proto.RegisterFile("block.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbd, 0x4e, 0xc3, 0x30,
	0x10, 0xc7, 0xe5, 0xd6, 0x4d, 0xe9, 0x15, 0x24, 0x74, 0x03, 0xf2, 0xc0, 0x10, 0x55, 0x0c, 0x9d,
	0x32, 0x90, 0x27, 0xe0, 0x63, 0x80, 0xa9, 0x51, 0x82, 0xd8, 0xf3, 0x71, 0xa2, 0x81, 0xca, 0xae,
	0x5c, 0x07, 0xf1, 0x14, 0xbc, 0x12, 0xaf, 0x86, 0x7c, 0xb6, 0x85, 0xd8, 0xee, 0xf7, 0xff, 0x25,
	0xf6, 0xff, 0x0c, 0xeb, 0xee, 0x60, 0xfa, 0x8f, 0xe2, 0x68, 0x8d, 0x33, 0x38, 0xd3, 0xe5, 0xe6,
	0x5b, 0xc0, 0x59, 0x53, 0xed, 0x5e, 0xa6, 0xe3, 0x81, 0x50, 0xc1, 0xb2, 0x99, 0xba, 0x77, 0xea,
	0x9d, 0x12, 0xb9, 0xd8, 0xae, 0xea, 0x84, 0x78, 0x05, 0xd9, 0x2e, 0x88, 0x19, 0x8b, 0x48, 0x78,
	0x0d, 0xab, 0xca, 0xd2, 0x30, 0xf6, 0xad, 0x23, 0x35, 0x67, 0xf5, 0x17, 0xf8, 0xf3, 0x5e, 0xc9,
	0x9e, 0x46, 0xa3, 0x95, 0xcc, 0xc5, 0x56, 0xd6, 0x09, 0xbd, 0x79, 0x30, 0xda, 0xd1, 0x97, 0x53,
	0x8b, 0x70, 0x53, 0xc4, 0xcd, 0x8f, 0x80, 0xc5, 0xbd, 0x2f, 0xe9, 0xbf, 0xe1, 0xe1, 0x79, 0x48,
	0x6d, 0x22, 0x62, 0x0e, 0xf2, 0xb1, 0x75, 0x2d, 0x77, 0x59, 0xdf, 0x9e, 0x17, 0xba, 0x2c, 0xd2,
	0x0e, 0x35, 0x1b, 0xbc, 0x81, 0x8b, 0xca, 0xd2, 0x27, 0xff, 0xf0, 0xd4, 0x9e, 0xf6, 0xb1, 0xdb,
	0xff, 0x10, 0x11, 0x24, 0x4b, 0xc9, 0x92, 0x67, 0xbc, 0x84, 0x79, 0x33, 0xbe, 0xc5, 0x56, 0x7e,
	0xf4, 0xbb, 0xdf, 0x4d, 0x6e, 0x6f, 0xac, 0xca, 0xc2, 0xee, 0x81, 0x7c, 0xde, 0x90, 0x1e, 0xc8,
	0xaa, 0x65, 0xc8, 0x03, 0x75, 0x19, 0xbf, 0x6e, 0xf9, 0x1b, 0x00, 0x00, 0xff, 0xff, 0x01, 0xd6,
	0x82, 0x0b, 0x6c, 0x01, 0x00, 0x00,
}
